feat: Event listing for administration
et-dagen/et-dagen pull request #124
Opened 2023-11-03 17:07 UTC by ipeglin

**Changes**
A list view of events stored in the database. The list shows a simple-detailed list of all event properties, and provides the option to edit or delete each event.

2023-12-28 23:15 UTC, AasmundN requested changes
Looks super smooth! Can we set the overflow of the two boxes mentioned below to scroll? Think it looks ugly when the elements are all bunched up, as they will be on mobile.

2023-12-28 23:26 UTC, AasmundN commented on pages/admin/events.vue
> +      <div>
This div

2023-12-28 23:27 UTC, AasmundN commented on pages/admin/events.vue
> +    <div class="d-flex align-center justify-space-between flex-wrap">
And this one

2023-12-29 14:53 UTC, ipeglin commented
> Looks super smooth! Can we set the overflow of the two boxes mentioned below? Think it looks ugly when the elements are all bunched up, as they will be on mobile.

Not sure if I fully understand. Would you like the overflow to be set to hidden?

2023-12-29 22:46 UTC, AasmundN commented
I meant the wrapping in these two elements. But it's not imortant.

<img width="250" alt="overflow" src="https://github.com/et-dagen/et-dagen/assets/48122613/7b0ae685-d3f1-4ebf-91a4-346836a89b7d">

2023-12-29 22:46 UTC, AasmundN approved these changes

2023-12-30 23:55 UTC, merged