130 overlapping sections on landing page
et-dagen/et-dagen pull request #157
Opened 2023-12-21 00:08 UTC by JStoresund

Solution: changed some styling in the companyhero component; the changes are inspired by the companycard component styling.

2023-12-21 11:23 UTC, AasmundN reviewed
The bottom of the company hero text was still cut off. Think I fixed it. Someone else will have to review.

2023-12-21 15:42 UTC, ipeglin requested changes
I think it looks really good. But I think we can increase the logo size a bit, and truncate the description when companyName + description exceeds the height of the logo

2023-12-21 15:42 UTC, ipeglin commented on components/company/Hero.vue
> +    <VCard :width="xs ? '90vw' : '65vw'" md="50v" variant="flat">
I think we should set a max height for every viewport. When the height is the same as this defined limit, for any given viewport, the description should be truncated with `nowrap` and `ellipsis`

2023-12-29 22:25 UTC, AasmundN approved these changes
Nice! Looks better. But if the text overflows, where is the user supposed to read the rest of it? Maybe on a separate page, idk.

2023-12-31 12:18 UTC, merged