feat: Edit company list
et-dagen/et-dagen pull request #191
Opened 2023-12-30 23:54 UTC by ipeglin

# Changes
## Frontend
* New file-input component to upload files
* New company edit component, very similar to that of #146. Allows for separately updating logo, without updating other values.

## Server
* `/api/component (DELETE)`: Adding code to delete company files in storage bucket
* `/api/component/logo (POST)`: New API endpoint for uploading company logo to storage bucket with path `companies/{CompanyUID}/logo.{png | jpg | jpeg}`.

2023-12-31 10:44 UTC, AasmundN requested changes
Awesome work 👏 

Also, for some reason, when I create a new company with logo and click on the new image on the home page it redirects back to localhost:3000, and not the website like it should.

And need  to add support for .JPG (uppercase).

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +  const { hasAccess, user } = useAuthStore()
Destructuring like this will not preserve reactivity. You can use `storeToRefs(...)` to do this.

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +    navigateTo('/company/edit')
Need to preserve locale with localePath.

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +  // Fetch event data if props are provided
Exchange event with company. Also for some of the other comments.

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +        setTimeout(() => navigateTo('/admin/companies'), 2000)
Localepath

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +  const createEvent = async () => {
createCompany

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +      .then(() => updateLogo()) // add logo newly created company if provided
I don't know why, but this doesn't seem to run when creating a new company. I have to go and add the logo with the _update logo_ button after creating the company.

2023-12-31 10:44 UTC, AasmundN commented on components/company/EditForm.vue
> +          <VBtn
I don't really understand why theres a separate button for updating the logo. I think this should be moved to the _save changes_ button.

2023-12-31 10:44 UTC, AasmundN commented on server/api/company/logo/index.post.ts
Nice, this seems to work well. However, I don't like that we depend on the UID of a company for uploading the logo. I think these should be as separate as possible. For example by passing a folder name to endpoint (just for some structuring of the files) and then we can create a new unique id just for the image, and then just save this as the logo in the company database. Or something similar. This way you don't have to create the company first before uploading an image.

Furthermore I think we should change the endpoint to be as general as possible. Maybe `POST /api/image`. This way we can reuse the endpoint if we need to upload other images, for example the contact page portraits.

2023-12-31 15:03 UTC, ipeglin commented
> Awesome work 👏
> 
> Also, for some reason, when I create a new company with logo and click on the new image on the home page it redirects back to localhost:3000, and not the website like it should.
> 
> And need to add support for .JPG (uppercase).

* **Fix:** The routing issue was caused due to navigating to `company.website`, when the proper property is `company.webpage`.
* **Fix:** Adding support for .JPG by properly checking for filetypes such as `image/png` and `image/jpeg` (which includes .JPG and .jpeg)

2023-12-31 16:24 UTC, AasmundN requested changes
Much better. However, I still think that the image API / file storage should not have any of the UIDs of for example a company. Having the relationship the other way around (images having their own id, and then store this id in for example a company), might be more general. Then we could have another endpoint for removing images from storage, which would be called when removing companies etc. This is nitpicking though. Might not be necessary.

2023-12-31 16:24 UTC, AasmundN commented on components/company/EditForm.vue
> +                @click="state.logo = null"
I think it is a little unclear what this button does. It seems like it deletes the logo, but what it actually does is just clear the form input. I think the button should not be red and use a different icon to make this more clear.

2024-01-02 17:52 UTC, AasmundN submitted a review, later dismissed
Nice, great work. Remember to merge dev.

2024-01-02 19:06 UTC, merged