222 eventid page
et-dagen/et-dagen pull request #250
Opened 2024-01-11 12:43 UTC by JStoresund

Route for showing information about a chosen event. Design inspired by tihlde.org's [event page](https://tihlde.org/arrangementer/704/arets-forste-gratis-klatring/).

2024-01-13 07:19 UTC, JStoresund commented
**Done:**
simple layout for event information. 

**Todo:** 
Fetch db data for company and registered users (for now it only says companyUID and userUIDs)

2024-01-23 21:44 UTC, AasmundN requested changes
This looks great. Just change it so the links on the programme page navigate to /event/id and not /program/id. We also need to rename the /program page to /programme.

2024-01-23 21:44 UTC, AasmundN commented on pages/event/[id].vue
> +        <strong>{{ $t('event.page.details.host') }}:</strong>
Add space

2024-01-24 10:15 UTC, AasmundN approved these changes

2024-01-24 10:15 UTC, merged