feat: event signup and optout deadline
et-dagen/et-dagen pull request #277
Opened 2024-01-26 23:44 UTC by ipeglin

## Changes
* Events with a capacity now has to declare a signup time window. Outside this window, a user cannot sign up or opt out of events

2024-01-27 14:44 UTC, JStoresund approved these changes
LGTM

2024-01-30 18:57 UTC, AasmundN requested changes
An event page must display when the registration opens and closes.

2024-01-30 19:02 UTC, AasmundN commented on pages/event/[id].vue
> +  const showRegistrationAction = ref(false)
This needs to be modified in order to show the button correctly on SSR.

2024-01-30 19:05 UTC, AasmundN reviewed
When you are registered for the event and the registration closes you still need to be able to see whether or not you are registered, now it just says that registration is not open.

2024-01-30 19:09 UTC, AasmundN commented
Admins shuld be able to register users (both their own user and other users) to an event. We should add a input field for entering a user id for registration on the event edit page.

2024-01-30 21:04 UTC, AasmundN commented
I added so that admins can register users to events at will.

2024-01-31 11:35 UTC, AasmundN approved these changes

2024-01-31 13:34 UTC, JStoresund approved these changes
LGTM!

2024-01-31 13:34 UTC, merged