feat: card grid
et-dagen/et-dagen pull request #289
Opened 2024-01-27 15:22 UTC by ipeglin

## Changes
* Adding abs position
* Removing unwanted wrapping of logos in grid

2024-01-30 18:19 UTC, AasmundN requested changes
Nice. The logos need to be smaller on mobile though, looks chaotic.

2024-01-31 10:01 UTC, JStoresund requested changes

2024-01-31 13:50 UTC, AasmundN approved these changes

2024-01-31 13:51 UTC, JStoresund approved these changes
LGTM!

2024-01-31 14:03 UTC, merged