feat: added custom error page
et-dagen/et-dagen pull request #72
Opened 2023-08-31 11:23 UTC by JStoresund

This PR is the first draft of a custom error page. The page consists of an outlined box in the middle with some describing text. The text inside the container is made as follows:

1. "Oops"
2. Error code
3. Error message
4. Link to front page

There is one version of the error page for mobile users, and one for computer users. For now they are very similar, only having slightly different text styling. Having one version for each is practical for further improvements if that is needed/wanted.

2023-08-31 11:25 UTC, JStoresund commented on components/error/errorCardMobile.vue
> +  defineProps(['error'])
Jeg får problemer med at 'error' burde typedefineres. Har forsøk litt ulike ting, men får alltid klager ('error' er av typen Object(), men får ikke til å legge det inn).

2023-08-31 18:38 UTC, AasmundN requested changes
Great work so far! I think that the error card component should be one component, no need to separate into one version for mobile and one for desktop. Instead you can use _@media queries_ or the _useDisplay_ composable to dynamically update the styles. However I believe Vuetify component VCard would adjust some its styles automatically out of the box.

2023-08-31 18:38 UTC, AasmundN commented on components/error/errorCard.vue
> +    style="
Inline styles like this are fine for only adding one or two attributes. But for adding a lot of styles like this you should make a class and place the styles in the `<style scoped></style>` tag.

2023-08-31 18:38 UTC, AasmundN commented on components/error/errorCardMobile.vue
> +    <h1 class="text-h2 font-weight-bold" style="color: orange">Oops!</h1>
I believe Vuetify has utility classes for setting text color as well.

2023-08-31 18:38 UTC, AasmundN commented on components/error/errorCardMobile.vue
> +  <div
Maybe use the Vuetify `VCard` component in order to have consistent styling with the rest of the application.

2023-09-04 20:04 UTC, AasmundN reviewed
Much better! I can seem to get the _error.vue_ page to render, so that will need some looking into. The 404 page is looking smashing! Remember to merge the dev branch into this branch🙌

2023-09-04 20:04 UTC, AasmundN commented on error.vue
> +    <v-sheet class="text-center">
Nice! One thing to take note of is that we always PascalCase for component names. So `VSheet` and not `v-sheet`. Even though both are valid syntax it is smart to keep to established conventions.

2023-09-04 20:04 UTC, AasmundN commented on error.vue
> +<script setup>
You will have to add `lang='ts'` in order to use typescript here.

2023-09-04 20:04 UTC, AasmundN commented on pages/[...slug].vue
> +      <v-btn @click="navigateTo('/')">Tilbake til forsiden</v-btn>
Remember to localize navigation!

2023-09-04 20:04 UTC, AasmundN commented on pages/[...slug].vue
> +    max-width: 90vw;
🤩

2023-09-06 15:03 UTC, JStoresund reviewed
Most of the changes made in this draft are fixes which were requested from the previous draft. 

A notable problem with the last draft was that upon creating a custom error, the error.vue page didn't show as it should. With some digging into the problem, it is deducable that ***the error.vue page only shows when the error is on the client side***. By adding the code 

´´´
throw createError({
    statusCode: 420,
    statusMessage: 'lmao',
  })
´´´

inside for example _server/middleware/auth.ts_ (or any other typescript file inside the server directory), error.vue does NOT show up.

On the contrary, if the above code is inserted into the script tag in _pages/index.vue_, the error.vue page will indeed be rendered. Hence the conclusion that the error has to be on the client side.

2023-09-08 08:05 UTC, AasmundN approved these changes
This looks good!

2023-09-08 10:59 UTC, merged