feat: 79 banner component
et-dagen/et-dagen pull request #80
Opened 2023-09-05 19:30 UTC by ipeglin

⚠️ Must be merged after #73 

# Changes
* New home/Banner component to greet users at landing page

# Remaining work
* Styling
* Call-to-action?

2023-09-09 11:32 UTC, AasmundN requested changes
Looking good. Maybe the text should be a tad bit larger? Also could we find a way to include the image on mobile view too? Might be hard to find a way that looks good I guess.

2023-09-09 11:32 UTC, AasmundN commented on components/home/Banner.vue
> +    @media (max-width: 768px) {
I think we should use the Vuetify breakpoints to make sure everything is consistent. 

```scss
@use 'vuetify/settings';

@media #{map-get(settings.$display-breakpoints, 'sm-and-down')} {
   // styles for sm breakpoint and down 
}
```

2023-09-09 11:32 UTC, AasmundN commented on pages/index.vue
>      <p>User from store: {{ user }}</p>
Think we can remove this, as well as the create user button and script tag.

2023-09-09 11:32 UTC, AasmundN commented on components/home/Banner.vue
> +    <v-img
PascalCase

2023-09-09 11:32 UTC, AasmundN commented on components/home/Banner.vue
> +      <h3>
Might want to use Vuetify text size classes.

2023-09-09 11:32 UTC, AasmundN commented on components/home/Banner.vue
> +  const startDate: DateStringObject = dateStringToStringObject(
Could use a computed property here to preserve reactivity, but I guess it's not really necessary.

2023-09-09 11:32 UTC, AasmundN commented on components/home/Banner.vue
> +    > * {
Cool

2023-09-10 15:00 UTC, ipeglin commented
> Looking good. Maybe the text should be a tad bit larger? Also could we find a way to include the image on mobile view too? Might be hard to find a way that looks good I guess.
> 
> One thing to keep in mind when using the `useDisplay` composable is that the server has no way of knowing much about the users device. So server side rendering depending on the composable will not really work. For some things this is fine, as long as one keeps it mind. Maybe by adding some transitions. In this case I think it would be better to use a @media query.

Made the required changes with the exception of the `useMobile` composable. I haven't really looked into the use of vuetify yet, so it would be nice if you could walk me through it in person some time.

2023-09-20 13:26 UTC, AasmundN approved these changes
I have made a few minor changes: 
- Added a border shadow to the image, which makes it pop out a bit more, and rounded its corners. 
- Changed the header elements so that the text will be smaller. Also added the Vuetify text size classes to these elements in `main.scss`.
- Fixed the locale switch page transition problem from #99 

Think this is good to go now.

2023-09-20 15:07 UTC, ipeglin commented
I'll add the call-to-action and anchor nav features to new issues, and merge this PR

2023-09-20 15:09 UTC, merged