Feature/90 feat signup form
et-dagen/et-dagen pull request #92
Opened 2023-09-13 18:58 UTC by ipeglin

# Changes
* New Signup component for registering users
* Signup button that registeres a new user in the database
* New SelectInput component for selecting study programs and current year
* New TextInput component for providing name in form

# Might change
* Remove Select and Text input components in favour of using the vuetify components directly in the form component.

2023-09-18 18:03 UTC, ipeglin commented on components/user/SignupForm.vue
> +    userType: 'student',
I'm setting the default userType to undefined as of now. I can change it later somewhere down the road if it is needed

2023-09-18 18:17 UTC, ipeglin commented on components/user/SignupForm.vue
> +    <v-container>
I'm going to work on this during the workshop on tuesday

2023-09-18 18:20 UTC, ipeglin commented on components/user/TextInput.vue
I agree. This draft is only a work-in-progress, so it is by no means finished :) I'll have a look at it tomorrow

2023-10-04 07:54 UTC, AasmundN commented
Need to wait for #102 too. I'll have it done before next meeting.

2023-10-06 11:37 UTC, AasmundN requested changes
I fixed some missing translations and added a max-width to the form. After merging #102 and fixing error handling of the `registerUser` function this should be good to go.

2023-10-06 11:37 UTC, AasmundN commented on components/user/SignupForm.vue
> +      await registerUser({
The registerUser function will throw errors if something goes wrong. These must be handled with _trycatch_ blocks and proper feedback to the user through some sort of popup.

2023-10-10 14:55 UTC, AasmundN approved these changes
LGTM

2023-10-10 14:57 UTC, merged